/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package le;

import com.digitalpersona.uareu.Reader;
import com.digitalpersona.uareu.UareUException;
import javax.swing.JDialog;

/**
 *
 * @author admin@emapa.lan
 */
public class Caracteristicas extends javax.swing.JPanel {

    /**
     * Creates new form Caracteristicas
     */
    
    
    public Caracteristicas( Reader reader) {
        
        initComponents();
        String str;
        
        
        Reader.Description rd = reader.GetDescription();
	str = String.format("Vendor name: %s\n", rd.id.vendor_name);
        txtArea.append(str);
        str = String.format("Product name: %s\n", rd.id.product_name);
        txtArea.append(str);
        str = String.format("Serial number: %s\n", rd.serial_number);
        txtArea.append(str);
        str = String.format("USB VID: %s\n", rd.id.vendor_id);
        txtArea.append(str);
        str = String.format("USB PID: %s\n", rd.id.product_id);
        txtArea.append(str);
        str = String.format("USB BCD revision: %s\n", rd.version.bcd_revision);
        txtArea.append(str);
        str = String.format("HW version: %d.%d.%d\n", rd.version.hardware_version.major, rd.version.hardware_version.minor, rd.version.hardware_version.maintenance);
        txtArea.append(str);
        str = String.format("FW version: %d.%d.%d\n", rd.version.firmware_version.major, rd.version.firmware_version.minor, rd.version.firmware_version.maintenance);
        txtArea.append(str);

        try{
                //open reader
                reader.Open(Reader.Priority.COOPERATIVE);

                //acquire capabilities
                Reader.Capabilities rc = reader.GetCapabilities();

                //close reader
                reader.Close();

                //print out capabilities
                txtArea.append("\n");
                str = String.format("can capture image: %b\n", rc.can_capture);
                txtArea.append(str);
                str = String.format("can stream image: %b\n", rc.can_stream);
                txtArea.append(str);
                str = String.format("can extract features: %b\n", rc.can_extract_features);
                txtArea.append(str);
                str = String.format("can match: %b\n", rc.can_match);
                txtArea.append(str);
                str = String.format("can identify: %b\n", rc.can_identify);
                txtArea.append(str);
                str = String.format("has fingerprint storage: %b\n", rc.has_fingerprint_storage);
                txtArea.append(str);
                str = String.format("indicator type: 0x%08x\n", rc.indicator_type);
                txtArea.append(str);
                str = String.format("has power management: %b\n", rc.has_power_management);
                txtArea.append(str);
                str = String.format("has calibration: %b\n", rc.has_calibration);
                txtArea.append(str);
                str = String.format("PIV compliant: %b\n", rc.piv_compliant);
                txtArea.append(str);
                for(int i = 0; i < rc.resolutions.length; i++){
                        str = String.format("resolution: %d dpi\n", rc.resolutions[i]);
                        txtArea.append(str);
                }
        } 
        catch(UareUException e){ 
                MessageBox.DpError("Reader.GetCapabilities()", e); 
        }
		
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtArea = new javax.swing.JTextArea();
        btnRegresar = new javax.swing.JButton();

        txtArea.setColumns(20);
        txtArea.setRows(5);
        jScrollPane1.setViewportView(txtArea);

        btnRegresar.setText("<< REGRESAR");
        btnRegresar.setToolTipText("");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 662, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addComponent(btnRegresar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addComponent(btnRegresar)
                .addContainerGap(63, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // TODO add your handling code here:
        m_dlgParent.setVisible(false);
    }//GEN-LAST:event_btnRegresarActionPerformed

    
    private JDialog m_dlgParent;
    
    private void doModal(JDialog dlgParent){
		m_dlgParent = dlgParent;
		m_dlgParent.setContentPane(this);
		m_dlgParent.pack();
		m_dlgParent.setLocationRelativeTo(null);
		m_dlgParent.toFront();
		m_dlgParent.setVisible(true);
		m_dlgParent.dispose();
	}
	
    public static void Show(Reader reader){
        JDialog dlg = new JDialog((JDialog) null, "Caracteristicas",true);
        Caracteristicas capabilities = new Caracteristicas(reader);
    	capabilities.doModal(dlg);
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegresar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtArea;
    // End of variables declaration//GEN-END:variables
}
