/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package le;

import com.digitalpersona.uareu.Reader;
import com.digitalpersona.uareu.ReaderCollection;
import com.digitalpersona.uareu.UareUException;
import java.util.Vector;
import javax.swing.JDialog;
import javax.swing.JList;

/**
 *
 * @author admin@emapa.lan
 */
public class Selection extends javax.swing.JPanel {

    /**
     * Creates new form Selection
     */
    
    private ReaderCollection m_collection; 
    private JList m_listReaders;
    private JDialog m_dlgParent;
    
    public Selection(ReaderCollection collection) {
        m_collection= collection;
        initComponents();
    }
    
     private void doModal(JDialog dlgParent){
            RefreshList();
            m_dlgParent = dlgParent;
            m_dlgParent.setContentPane(this);
            m_dlgParent.pack();
            m_dlgParent.setLocationRelativeTo(null);
            m_dlgParent.toFront();
            m_dlgParent.setVisible(true);
            m_dlgParent.dispose();
    }
    
    public Reader getSelectedReader(){
            if(-1 == jList1.getSelectedIndex()) return null;
            return m_collection.get(jList1.getSelectedIndex());
    }
    
    private void RefreshList(){
		//acquire available readers
        try{
                m_collection.GetReaders();
        } 
        catch(UareUException e) { 
                MessageBox.DpError("ReaderCollection.GetReaders()", e);
        }

        //list reader names
        Vector<String> strNames = new Vector<String>();
        for(int i = 0; i < m_collection.size(); i++){
                strNames.add(m_collection.get(i).GetDescription().id.product_name);
        }
        jList1.setListData(strNames);
    }
    
    public static Reader Select(ReaderCollection collection){
    	
        JDialog dlg = new JDialog((JDialog)null, "Seleccionar lector", true);
    	Selection selection = new Selection(collection);
    	selection.doModal(dlg);
        return selection.getSelectedReader();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        btnRecargar = new javax.swing.JButton();
        btnVer = new javax.swing.JButton();
        btnAtras = new javax.swing.JButton();

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        btnRecargar.setText("Recargar");
        btnRecargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecargarActionPerformed(evt);
            }
        });

        btnVer.setText("Ver Caracteristicas");
        btnVer.setToolTipText("");
        btnVer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerActionPerformed(evt);
            }
        });

        btnAtras.setText("<< Regresar");
        btnAtras.setToolTipText("");
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAtras)
                    .addComponent(btnVer)
                    .addComponent(btnRecargar)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRecargar)
                .addGap(18, 18, 18)
                .addComponent(btnVer)
                .addGap(18, 18, 18)
                .addComponent(btnAtras)
                .addContainerGap(40, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnRecargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecargarActionPerformed
        // TODO add your handling code here:
        this.RefreshList();
    }//GEN-LAST:event_btnRecargarActionPerformed

    private void btnVerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerActionPerformed
        // TODO add your handling code here:
        Reader reader = this.getSelectedReader();
        if(reader!=null) Caracteristicas.Show(reader);
    }//GEN-LAST:event_btnVerActionPerformed

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        // TODO add your handling code here:
        m_dlgParent.setVisible(false);
    }//GEN-LAST:event_btnAtrasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnRecargar;
    private javax.swing.JButton btnVer;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
